# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_type',
            field=models.CharField(blank=True, choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('UNDER REVEIW', 'UNDER REVIEW'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('SALARIED', 'SALARIED'), ('SELF-EMPLOYED', 'SELF-EMPLOYED')], default=0, max_length=250),
        ),
    ]
