# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_sanctioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('SANCTIONED', 'SANCTIONED'), ('NOT-SANCTIONED', 'NOT-SANCTIONED')], default=0, max_length=250),
        ),
    ]
