# Generated by Django 4.1.6 on 2023-02-10 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', '')], default='', max_length=50)),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default=0, max_length=250)),
                ('father_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_name', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('marital_status', models.CharField(blank=True, choices=[('', '')], default=0, max_length=250)),
                ('spouse_name', models.CharField(blank=True, default=0, max_length=250)),
                ('spouse_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('address', models.TextField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Familys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
