# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('UNMARRIED', 'UNMARRIED'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], default=0, max_length=250),
        ),
    ]
