# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disburstment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DISBURSED', 'DISBURSED')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='pending', max_length=100),
        ),
    ]
